### ISSUE TITLE
Yao APIs for 'measure', 'reset' and 'barrier'

### ISSUE THREAD

**Issue by thautwarm** [QuantumBFS/YaoQASM.jl#4]
Check https://github.com/QuantumBFS/YaoQASM.jl/blob/master/src/grammar.jl for what I haven't implemented yet(each of these constructs is marked with a trailing `# not impl`)

**Comment by GiggleLiu** [comment]
Is it possible to use placeholders first, some printing blocks. It disentangles the developments and easier for debugging.

Then, I can figure out how to implement these placeholders.

**Comment by thautwarm** [comment]
Okay, will do it.

**Comment by thautwarm** [comment]
this get fixed already?

**Comment by Roger-luo** [comment]
yes, fixed.
