### ISSUE TITLE
Issues with the current version of Yao.jl

### ISSUE THREAD

**Issue by VarLad** [QuantumBFS/YaoQASM.jl#8]
Just downgrades most of my packages related to Yao when I add YaoQASM to Julia

**Comment by Roger-luo** [comment]
Hi this package is not compatible with the latest version (due to a few changes). Also have you tried the master branch?

**Comment by VarLad** [comment]
Thanks for the reply
Just tried the master branch. The version from the master branch seems to be 0.1.1 and is still equally incompatible.

**Comment by Roger-luo** [comment]
I see. I think there are still several blocks not updated for the latest YaoBlocks representation.

**Comment by Roger-luo** [comment]
I'm going to close this since I'll be moving this to the new parser in OpenQASM.
